apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-stable
  namespace: {{ .Values.namespace.name }}
  labels:
    app: demo
    version: {{ .Values.stable.appVersion }}
spec:
  replicas: {{ .Values.stable.replicas }}
  selector:
    matchLabels:
      app: demo
      version: {{ .Values.stable.appVersion }}
  template:
    metadata:
      labels:
        app: demo
        version: {{ .Values.stable.appVersion }}
    spec:
      containers:
        - name: demo
          image: "{{ .Values.image.repository }}:{{ .Values.stable.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: APP_VERSION
              value: "{{ .Values.stable.appVersion }}"
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
